version: '2.0'
services:
  prometheus:
    container_name: prometheus       
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    user: "root"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus 
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: always
    logging:
      options:       
        max-file: "1"
        max-size: "1m"  

  grafana:
    container_name: grafana      
    image: grafana/grafana:latest
    user: "104"
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana  
      - ./grafana/:/etc/grafana/
    links:
      - prometheus:prometheus
    depends_on:
            - prometheus    
    logging:
      options:       
        max-file: "1"
        max-size: "1m"   

  loki:
    container_name: loki
    ports:
      - 3100:3100    
    image: grafana/loki:latest
    restart: always
    links:
      - prometheus:prometheus
    depends_on:
      - prometheus
    #command: -config.file=/etc/loki/local-config.yaml   
    logging:
      options:       
        max-file: "1"
        max-size: "1m"       

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    #command: -config.file=/etc/promtail/docker-config.yaml

volumes:
        prometheus_data: {}
        grafana_data: {}   
