version: '2.0'
services:
  prometheus:
    container_name: prometheus       
    network_mode: bridge
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    user: "root"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus 
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: always
    logging:
      options:       
        max-file: "1"
        max-size: "1m"  

  grafana:
    container_name: grafana      
    network_mode: bridge       
    image: grafana/grafana:latest
    user: "104"
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana  
      - ./grafana/:/etc/grafana/
    links:
      - prometheus:prometheus
    depends_on:
            - prometheus    
    logging:
      options:       
        max-file: "1"
        max-size: "1m"       

  nginx:
    container_name: nginx      
    network_mode: bridge        
    image: nginx:latest
    ports:
      - 443:443
    restart: always
    volumes:  
      - ./nginx/:/etc/nginx/
    links:
      - prometheus:prometheus
    depends_on:
            - prometheus    
    logging:
      options:       
        max-file: "1"
        max-size: "1m"       

volumes:
        prometheus_data: {}
        grafana_data: {}   
