version: '2.0'
services:
  prometheus:
    network_mode: bridge
    image: evns/rpi-prometheus
    expose:
      - "9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus 
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=https://localhost/prometheus
      - --web.route-prefix=/
    restart: always
    logging:
      options:       
        max-file: "1"
        max-size: "1m"  

  grafana:
    network_mode: bridge       
    image: grafana/grafana:latest
    user: "104"
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana  
      - ./grafana/:/etc/grafana/
    links:
      - prometheus:prometheus
    depends_on:
            - prometheus    
    logging:
      options:       
        max-file: "1"
        max-size: "1m"       

  nginx:
    network_mode: bridge        
    image: nginx:latest
    ports:
      - 443:443
    restart: always
    volumes:  
      - ./nginx/:/etc/nginx/
    links:
      - prometheus:prometheus
    depends_on:
            - prometheus    
    logging:
      options:       
        max-file: "1"
        max-size: "1m"       

  blackbox_exporter:
    network_mode: bridge
    image: p0sa/blackbox_exporter_pi:latest
    restart: always
    ports:
      - 9115:9115
    links: 
      - prometheus:prometheus
    depends_on:
            - prometheus   
    logging:
      options:       
        max-file: "1"
        max-size: "1m"       
 

volumes:
        prometheus_data: {}
        grafana_data: {}   
