scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - prometheus-armv7:9090

  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - node-exporter-linux-armv7:9100

  - job_name: grafana
    scrape_interval: 5s
    static_configs:
      - targets:
          - grafana:3000

  - job_name: alertmanager
    scrape_interval: 5s
    static_configs:
      - targets:
          - alertmanager:9093