scrape_configs:
  - job_name: prometheus
    scrape_interval: 1s
    static_configs:
      - targets:
          - localhost:9090

  - job_name: cAdvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:8080

  - job_name: grafana
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:3000

  - job_name: alertmanager
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:9093