scrape_configs:      

  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
     - targets:
             - localhost:9090
               
  - job_name: node_exporter
    scrape_interval: 15s
    static_configs:
     - targets:
         - 192.168.0.6:9100

  - job_name: grafana
    scheme: https
    tls_config:
            insecure_skip_verify: true
    scrape_interval: 15s
    static_configs:
      - targets:
          - 192.168.0.6:3000

            # - job_name: alertmanager
    # scrape_interval: 5s
    #  static_configs:
            # - targets:
              #         - 192.168.0.6:9093
          


  - job_name: loki
    scrape_interval: 5s
    static_configs:
        - targets: 
            - 192.168.0.6:3100


  - job_name: flowercare
    scrape_interval: 45s
    static_configs:
        - targets: 
            - 192.168.0.6:9294

