scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - 192.168.0.6:9100

  - job_name: grafana
    scrape_interval: 5s
    static_configs:
      - targets:
          - 192.168.0.6:3000

  - job_name: alertmanager
    scrape_interval: 5s
    static_configs:
      - targets:
          - 192.168.0.6:9093
